In [1]:
from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

In [2]:
imdb = Table.read_table('imdb.csv')
imdb.show(5)

# Question 1
Find the ten movies released in the year 2000 or later with the highest number of votes according to imdb.csv. Format your answer as a table with columns Title and Votes (in that order) of the three requested movies.

In [9]:
movies_2000 = imdb.where('Year', are.above_or_equal_to(2000)) 
movies_sorted = imdb.sort('Year', descending = True)
top_movies = movies_sorted.take(np.arange(0,10,1))
movies_title_votes = top_movies.select('Title','Votes')
movies_title_votes.show(10)

# Question 2

Create a table with columns Title and Votes containing all movies released in 1999.

Next, attach a new column to the table called Percent Votes that contains the percent of votes each movie received when considered among all votes cast for movies released in 1999.

For example, if the total number of votes cast for movies released in 1999 is 200 and "The Matrix" received 30 of them, then the column Percent Votes corresponding to "The Matrix" should 15.

In [11]:
movies_1999 = imdb.where('Year', 1999)
title_votes_1999 = movies_1999.select('Title', 'Votes')
votes_1999_array = title_votes_1999.column('Votes')
sum_votes_1999 = sum(votes_1999_array)
percent_votes = votes_1999_array / sum_votes_1999
final_table = title_votes_1999.with_column('Percent Votes', percent_votes)
final_table

Title           | Votes   | Percent Votes
Fight Club      | 1177098 | 0.274441
American Beauty | 735056  | 0.171379
The Sixth Sense | 630994  | 0.147117
The Matrix      | 1073043 | 0.250181
The Green Mile  | 672878  | 0.156882